export const MOCK_USERS = [
    {
        id: '1',
        username: 'design_ninja',
        full_name: 'Alex Rivera',
        avatar_url: 'https://i.pravatar.cc/150?u=1',
        bio: 'Product Designer & Coffee Enthusiast',
        followers: 1200,
        following: 450,
        posts_count: 24,
    },
    {
        id: '2',
        username: 'creative_mind',
        full_name: 'Sarah Chen',
        avatar_url: 'https://i.pravatar.cc/150?u=2',
        bio: 'Visual Explorer | UI/UX @ Visionary',
        followers: 3500,
        following: 800,
        posts_count: 56,
    },
];

export const MOCK_POSTS = [
    {
        id: '1',
        user_id: '1',
        creator: MOCK_USERS[0],
        title: 'Minimalist Dashboard Concept',
        description: 'A clean and minimal dashboard for project management.',
        image_url: 'https://picsum.photos/800/600?random=1',
        likes: 124,
        views: 1200,
        comments_count: 12,
        category: 'UI/UX',
        created_at: '2024-03-20T10:00:00Z',
    },
    {
        id: '2',
        user_id: '2',
        creator: MOCK_USERS[1],
        title: 'Brand Identity - EcoFlow',
        description: 'Visual identity for a sustainable energy startup.',
        image_url: 'https://picsum.photos/800/1000?random=2',
        likes: 450,
        views: 3500,
        comments_count: 45,
        category: 'Branding',
        created_at: '2024-03-19T15:30:00Z',
    },
    {
        id: '3',
        user_id: '1',
        creator: MOCK_USERS[0],
        title: 'Mobile Banking App',
        description: 'Dark mode exploration for a banking application.',
        image_url: 'https://picsum.photos/800/1200?random=3',
        likes: 320,
        views: 2800,
        comments_count: 28,
        category: 'Mobile',
        created_at: '2024-03-18T09:15:00Z',
    },
    {
        id: '4',
        user_id: '2',
        creator: MOCK_USERS[1],
        title: '3D Illustration Set',
        description: 'Abstract 3D elements for web design.',
        image_url: 'https://picsum.photos/1200/800?random=4',
        likes: 890,
        views: 12000,
        comments_count: 156,
        category: '3D Art',
        created_at: '2024-03-17T20:00:00Z',
    },
];

export const CATEGORIES = [
    'All', 'UI/UX', 'Branding', 'Illustration', 'Web Design', 'Mobile', 'Typography', '3D Art', 'Animation',
];

export const MOCK_NOTIFICATIONS = [
    {
        id: '1',
        type: 'like',
        user: MOCK_USERS[1],
        post: MOCK_POSTS[0],
        timestamp: '2m ago',
    },
    {
        id: '2',
        type: 'comment',
        user: MOCK_USERS[1],
        post: MOCK_POSTS[0],
        content: 'Love the color palette!',
        timestamp: '15m ago',
    },
    {
        id: '3',
        type: 'follow',
        user: MOCK_USERS[1],
        timestamp: '1h ago',
    },
];
