export const MOCK_USERS = [
    {
        id: '1',
        username: 'design_ninja',
        full_name: 'Alex Rivera',
        avatar_url: 'https://i.pravatar.cc/150?u=1',
        bio: 'Product Designer & Coffee Enthusiast',
        followers: 1200,
        following: 450,
        posts_count: 24,
        is_verified: true,
        location: 'San Francisco, CA',
        cover_image_url: 'https://picsum.photos/800/200?random=1',
    },
    {
        id: '2',
        username: 'creative_mind',
        full_name: 'Sarah Chen',
        avatar_url: 'https://i.pravatar.cc/150?u=2',
        bio: 'Visual Explorer | UI/UX @ Visionary',
        followers: 3500,
        following: 800,
        posts_count: 56,
        is_verified: false,
        location: 'New York, NY',
        cover_image_url: 'https://picsum.photos/800/200?random=2',
    },
    {
        id: '3',
        username: 'pixel_art',
        full_name: 'Mike Ross',
        avatar_url: 'https://i.pravatar.cc/150?u=3',
        bio: 'Freelance Illustrator',
        followers: 900,
        following: 200,
        posts_count: 15,
        is_verified: false,
        location: 'London, UK',
        cover_image_url: 'https://picsum.photos/800/200?random=3',
    },
];

export const MOCK_POSTS = [
    {
        id: '1',
        user_id: '1',
        creator: MOCK_USERS[0],
        title: 'Minimalist Dashboard Concept',
        description: 'A clean and minimal dashboard for project management.',
        image_url: 'https://picsum.photos/800/600?random=1',
        likes: 124,
        views: 1200,
        comments_count: 12,
        category: 'UI/UX',
        created_at: '2m ago',
        tags: ['minimal', 'dashboard', 'ui'],
    },
    {
        id: '2',
        user_id: '2',
        creator: MOCK_USERS[1],
        title: 'Brand Identity - EcoFlow',
        description: 'Visual identity for a sustainable energy startup.',
        image_url: 'https://picsum.photos/800/1000?random=2',
        likes: 450,
        views: 3500,
        comments_count: 45,
        category: 'Branding',
        created_at: '1h ago',
        tags: ['green', 'logo', 'branding'],
    },
    {
        id: '3',
        user_id: '1',
        creator: MOCK_USERS[0],
        title: 'Mobile Banking App',
        description: 'Dark mode exploration for a banking application.',
        image_url: 'https://picsum.photos/800/1200?random=3',
        likes: 320,
        views: 2800,
        comments_count: 28,
        category: 'Mobile Design',
        created_at: '3h ago',
        tags: ['fintech', 'darkmode', 'app'],
    },
    {
        id: '4',
        user_id: '2',
        creator: MOCK_USERS[1],
        title: '3D Illustration Set',
        description: 'Abstract 3D elements for web design.',
        image_url: 'https://picsum.photos/1200/800?random=4',
        likes: 890,
        views: 12000,
        comments_count: 156,
        category: '3D',
        created_at: '1d ago',
        tags: ['3d', 'blender', 'abstract'],
    },
    {
        id: '5',
        user_id: '3',
        creator: MOCK_USERS[2],
        title: 'Neon City',
        description: 'Cyberpunk inspired digital art.',
        image_url: 'https://picsum.photos/800/800?random=5',
        likes: 567,
        views: 5000,
        comments_count: 89,
        category: 'Illustration',
        created_at: '2d ago',
        tags: ['cyberpunk', 'neon', 'art'],
    },
    {
        id: '6',
        user_id: '2',
        creator: MOCK_USERS[1],
        title: 'Typography Experiment',
        description: 'Playing with bold serif fonts.',
        image_url: 'https://picsum.photos/900/1200?random=6',
        likes: 230,
        views: 2100,
        comments_count: 20,
        category: 'Typography',
        created_at: '3d ago',
        tags: ['type', 'font', 'serif'],
    },
];

export const CATEGORIES = [
    'All',
    'Logo',
    'UI/UX',
    'Branding',
    'Illustration',
    'Web Design',
    'Mobile Design',
    'Typography',
    'Photography',
    '3D',
    'Animation',
    'Print',
    'Packaging'
];

export const MOCK_NOTIFICATIONS = [
    {
        id: '1',
        type: 'like',
        user: MOCK_USERS[1],
        post: MOCK_POSTS[0],
        content: 'liked your post.',
        timestamp: '2m ago',
        read: false,
    },
    {
        id: '2',
        type: 'comment',
        user: MOCK_USERS[2],
        post: MOCK_POSTS[0],
        content: 'Love the color palette!',
        timestamp: '15m ago',
        read: false,
    },
    {
        id: '3',
        type: 'follow',
        user: MOCK_USERS[1],
        content: 'started following you.',
        timestamp: '1h ago',
        read: true,
    },
    {
        id: '4',
        type: 'mention',
        user: MOCK_USERS[0],
        post: MOCK_POSTS[1],
        content: 'mentioned you in a comment.',
        timestamp: '1d ago',
        read: true,
    },
];

export const MOCK_MESSAGES = [
    {
        id: '1',
        sender: MOCK_USERS[1],
        lastMessage: 'Hey! Are you open for a collab?',
        timestamp: '10:30 AM',
        unreadCount: 2,
    },
    {
        id: '2',
        sender: MOCK_USERS[2],
        lastMessage: 'Thanks for the resources!',
        timestamp: 'Yesterday',
        unreadCount: 0,
    },
];

export const MOCK_REVIEWS = [
    // ... reviews if needed
];

export const MOCK_COLLECTIONS = [
    {
        id: '1',
        name: 'Inspiration',
        count: 12,
        cover: MOCK_POSTS[0].image_url,
    },
    {
        id: '2',
        name: 'UI Trends 2024',
        count: 5,
        cover: MOCK_POSTS[2].image_url,
    },
];
